import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers';
import {tokenAddress, token2Address, tokenABI, factoryAddress, factoryABI, erc20ABI} from "./contracts_abi"
import TopBar from "../components/TopBar"

declare let window: any

export default class Home extends React.Component {
  state = {
    currentAccount: null,
    network: {
      avalancheFuji: {
          chainId: `0x${Number(43113).toString(16)}`,
          chainName: "Avalanche Fuji Testnet",
          nativeCurrency: {
              name: "AVAX",
              symbol: "AVAX",
              decimals: 18
          },
          rpcUrls: ["https://api.avax-test.network/ext/bc/C/rpc"],
          blockExplorerUrls: ["https://testnet.snowtrace.io/"]
      }
    },

    tokens: ["BTC", "LINK"],
    balance: [],
    prices: [],
    strikesDeadline: ["0","0"],
    
    btc_calls: 0,
    link_calls: 0,
  }

  componentDidMount = () => {
    //this.getDeadline()
  }
 
  getDeadline = async () => {
    const { ethereum } = window;
    if (ethereum) {
      
      const provider = new ethers.providers.Web3Provider(ethereum);
      const signer = provider.getSigner();

      let deadlines:any = []

      const tokenContract = new ethers.Contract(tokenAddress, tokenABI, signer);
      await tokenContract.getStrikeDeadline().then((strike:any ) =>{
        this.setState({deadlines:[ethers.utils.formatEther(strike).slice(0,6)]})
      })
      
    }else{
      console.log("Ethereum object does not exist");
    }
  }
  render(): React.ReactNode {
    return (
      <div className={styles.container}>

        <Head>
          <title>Loan & Options DApp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <main className={styles.main}>

          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Dopex!</a>
          </h1>
          <TopBar></TopBar>
          <div className={styles.grid}>
            {this.state.tokens.map( (item,i) => {
              return(
                <a className={styles.card}>
                  <h2>{item}
                    <span className=" bg-green-100 text-green-800 text-xs font-semibold ml-24 px-2.5 py-0.5 rounded dark:bg-green-200 dark:text-green-900">CALLS</span>  
                  </h2>
                  <ul className='ml-5 flex flex-wrap font-medium text-center text-gray-500'>
                    <li className='mr-2'>
                      <a className="inline-block p-4 text-blue-600 bg-gray-100 rounded-md active dark:bg-gray-800 dark:text-blue-500">
                        TVL:
                      </a>
                    </li>
                    <li className="mr-2">
                        <a className="inline-block p-4 text-blue-600 bg-gray-100 rounded-md active dark:bg-gray-800 dark:text-blue-500">Deposits:</a>
                    </li>
                  </ul>
                  <p className={styles.epoch}>Epoch: {this.state.strikesDeadline[i]}</p>
                  <button className='mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800'>
                    <a href={"/Calls/"+item}>Manage</a>
                  </button>
                </a>
              )
            } )}
          </div>
          <div className={styles.grid}>
            {this.state.tokens.map( (item,i) => {
              return(
                <a className={styles.card}>
                  <h2>{item}
                    <span className=" bg-red-100 text-red-800 text-xs font-semibold ml-24 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-red-900">PUTS</span>  
                  </h2>
                  <ul className='ml-5 flex flex-wrap font-medium text-center text-gray-500'>
                    <li className='mr-2'>
                      <a className="inline-block p-4 text-blue-600 bg-gray-100 rounded-md active dark:bg-gray-800 dark:text-blue-500">
                        TVL:
                      </a>
                    </li>
                    <li className="mr-2">
                        <a className="inline-block p-4 text-blue-600 bg-gray-100 rounded-md active dark:bg-gray-800 dark:text-blue-500">Deposits:</a>
                    </li>
                  </ul>
                  <p className={styles.epoch}>Epoch: {this.state.strikesDeadline[i]}</p>
                  <button className='mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800'>
                    <a href={"/Puts/"+item}>Manage</a>
                  </button>
                </a>
              )
            } )}
          </div>

        </main>
  
      </div>
    )
  }
  
}
